### ISSUE TITLE
Import self-created structured mesh-file

### ISSUE THREAD

**Issue by dominikstaltner** [jaheyns/CfdOF#11]
Hello guys,
is it possible to import a self-created structured mesh-file (e.g. .stl-file created in gmsh) to the CfdOF-workbench in FreeCAD?
Best regards
Dominik

**Comment by oliveroxtoby** [comment]
Hi Dominik

It is possible in principle - you can open the stl file in FreeCAD and use it as a surface the same way you would use a surface that you created in FreeCAD. However, it is not very practical if the surface contains even a moderate number of triangles, as each will be seen as a separate face when assigning boundary conditions and the process will quickly become impractical and/or slow.

Doing this in an elegant way is probably the most wanted feature of CfdOF right now. Personally I would like to see a way of grouping the faces of the imported stl into some sort of composite faces.

If you or anyone else has an interest in looking at this, it would be great.

**Comment by dominikstaltner** [comment]
Hello Oliver,

thanks a lot for your answer. It would be really cool if this will work in the future (like the import of .unv-files in the FEM-workbench).

Best regards
Dominik
