### ISSUE TITLE
HISA not found even after an installation attempt

### ISSUE THREAD

**Issue by Titi9237** [jaheyns/CfdOF#12]
Hi, 
I am trying to install HISA with the Freecad Preferences assistant and it is not working for me : 
![capture d ecran de 2019-01-15 15-46-14](https://user-images.githubusercontent.com/22113749/51187806-ee378b00-18dc-11e9-8d78-92dcc9ff43b9.png)

When using the Install HISA button, I end up with 
> Checking dependencies...
HiSA not found
Downloading HiSA, please wait...
Extracting HiSA...
Download completed
Building HiSA. Please wait...
Log file: /home/myusername /OpenFOAM/myusername-6/hisa-master/log.Allwmake
Install completed
Checking dependencies...
HiSA not found

The log.Allwmake yields many errors (see in attachments) 
[log.Allwmake.txt](https://github.com/jaheyns/CfdOF/files/2760092/log.Allwmake.txt)

I am using Ubuntu 18.04 and Freecad 0.17.

What am I doing wrong ? If you need any other info, feel free to ask.

Thanks

**Comment by oliveroxtoby** [comment]
It seems that I forgot to update the package of HiSA with the latest one updated for OF6. If you retry the installation now, is should be working.

**Comment by Titi9237** [comment]
Thanks, It seems to be fixed !

**Comment by Estay1991** [comment]
I encountered same problem. Hisa is not found after installation complete.

**Comment by oliveroxtoby** [comment]
> I encountered same problem. Hisa is not found after installation complete.

Please could you log a new issue, providing full information about how to reproduce your problem.

**Comment by Estay1991** [comment]
just logged a new issue.  https://github.com/jaheyns/CfdOF/issues/35
Please help.

Oliver Oxtoby <notifications@github.com> 于2020年6月24日周三 下午4:12写道：
