### ISSUE TITLE
Meshing exited with error

### ISSUE THREAD

**Issue by salicto** [jaheyns/CfdOF#144]
Hello,

I'm not here to update a bug, but rather with a question. Is there a way to view the mesh log file? I'm getting an error message that says 'Meshing exited with error' and I can't figure out where it's coming from. I have no output other than this.

> 
> Wrote mesh case to C:\Users\tom.salic\Desktop\OpenFoam_freecad\meshCase
> 16:03:15  Executing: ./Allmesh in C:\Users\tom.salic\Desktop\OpenFoam_freecad\meshCase
> 16:03:17  Setting environment for OpenFOAM 8 mingw-w64 Double Precision (of8-64), using MSMPI71 - please wait...
> 16:03:17  Environment is now ready. Notes:
>    - You can change between installed versions by running: ofmenu
>    - You can change to other predefined versions by running: ofmenuNew

cfdof v. 1.22.12
FreeCAD v. 0.20.0

Thanks in advance

**Comment by oliveroxtoby** [comment]
If there's a log file it will be in the directory C:\Users\tom.salic\Desktop\OpenFoam_freecad\meshCase, but it looks like it is failing before that point.

For support questions like this, please could I direct you to the forum https://forum.freecad.org/viewforum.php?f=37 and the information provided there. Hopefully someone can make a suggestion.
