### ISSUE TITLE
CfdOF not working with openfoam11

### ISSUE THREAD

**Issue by kolergy** [jaheyns/CfdOF#151]
Tried to install DfdOF on Freecad 0.21.1

I had previously installed openfoam11 which includes  paraview 510 
gmsh 4.8.4 was also installed

when performing the dependancy check I have this error;

OpenFOAM directory: /opt/openfoam11
14:27:36  Running  echo $WM_PROJECT_VERSION
14:27:36  Executing: echo $WM_PROJECT_VERSION in None
14:27:36  11
14:27:36  Traceback (most recent call last):
14:27:36    File "/home/me/.local/share/FreeCAD/Mod/CfdOF/./CfdOF/CfdPreferencePage.py", line 273, in runDependencyChecker
14:27:36      CfdTools.checkCfdDependencies(lambda msg:  (print(msg), self.consoleMessage(msg)))
14:27:36    File "/home/me/.local/share/FreeCAD/Mod/CfdOF/./CfdOF/CfdTools.py", line 1118, in checkCfdDependencies
14:27:36      msgFn("OpenFOAM version " + str(foam_ver) + " is not yet supported:\n" + \
14:27:36  TypeError: can only concatenate str (not "int") to str

**Comment by oliveroxtoby** [comment]
The issue with the error message should be fixed (I hope) but not that openfoam 11 is not yet supported unfortunately.
