### ISSUE TITLE
Bug reporting

### ISSUE THREAD

**Issue by Azazzeli** [jaheyns/CfdOF#152]
We ask that you please use this interface to contribute constructively to this free, open-source project by reporting carefully tested problems that you find in the software. Please provide as much information as you can and, if at all possible,
**include a small test case which allows developers to reproduce the issue**.
**
![image](https://github.com/jaheyns/CfdOF/assets/147992125/ffd19678-51b7-4f7c-b5e3-7423c4f3321a)
![image](https://github.com/jaheyns/CfdOF/assets/147992125/652d8dd8-05f7-44ba-8757-5f4eb985bfd0)
![image](https://github.com/jaheyns/CfdOF/assets/147992125/fabfc8d5-92e5-4501-9cf2-fbac838e73c6)
![Uploading image.png…]()

**Comment by Azazzeli** [comment]
Вот такая ошибка при попытке установить дополнение

**Comment by oliveroxtoby** [comment]
I'm unfortunately unable to reproduce this error, so I will need more information. Please see the forum post mentioned in the issue template for more information. It does look like it may be an issue that is more related to the FreeCAD addon manager than CfdOF, so it might be worth seeking help there.

**Comment by oliveroxtoby** [comment]
Closing due to lack of response. Feel free to reopen.
