### ISSUE TITLE
No module named 'freecad.plot'

### ISSUE THREAD

**Issue by numenic** [jaheyns/CfdOF#16]
Software Context
==============
Freecad was installed *via* conda: `conda create -n freecad freecad -c conda-forge`

Freecad about:

```
OS: Ubuntu 18.10
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.18.14555 (Git shallow)
Build type: Release
Branch: (HEAD detached at 2ea4c6a)
Hash: 2ea4c6a81a6449b6880f8a757d0298dd889e0630
Python version: 3.7.1
Qt version: 5.6.2
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: French/Switzerland (fr_CH)
```

cfdOF Dependancies
=================

Dependency checker output:

```
Checking dependencies...
No missing dependencies detected
```

Bug Occuring
===========

Performing first tutorial (elbow), everythong works fine until Page 22 (Write the case to a directory). Clicking on the "Edit Properties and run solver"  green arrow button raises the following stacktrace:

```
Traceback (most recent call last):
  File "/home/nic/.FreeCAD/Mod/CfdOF/_ViewProviderCfdSolverFoam.py", line 81, in setEdit
    from CfdRunnableFoam import CfdRunnableFoam
  File "/home/nic/.FreeCAD/Mod/CfdOF/CfdRunnableFoam.py", line 44, in <module>
    from CfdResidualPlot import ResidualPlot
  File "/home/nic/.FreeCAD/Mod/CfdOF/CfdResidualPlot.py", line 30, in <module>
    from freecad.plot import Plot
<class 'ModuleNotFoundError'>: No module named 'freecad.plot'
```

--------

[**edit**] No bug detected using freecad-daily

The Bug does not affect Freecad-daily
===============================

```
OS: Ubuntu 18.10
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.18.16093 (Git)
Build type: Release
Branch: releases/FreeCAD-0-18
Hash: 690774c0effe4fd7b8d2b5e2fb2b8c8d145e21ce
Python version: 2.7.15+
Qt version: 5.11.1
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: French/Switzerland (fr_CH)
```

**Comment by looooo** [comment]
Basically it was an experiment to externalize the plot / ship modules. I thought about replacing the internal modules, but I think keeping them outside the FreeCAD-source is better.

How to solve 3rd-party cross-dependencies, I don't know. I guess such things will occur sooner or later.

**Comment by numenic** [comment]
Closed (*cf*  https://github.com/jaheyns/CfdOF/issues/16#issuecomment-481280789)

**Comment by oliveroxtoby** [comment]
Thanks @looooo , that's good to know. I did not realise this had become a non-core dependency, so I will update our docs accordingly. There is a space to specify 3rd party dependencies in the addon manager's metadata, though I don't think it is used as yet.
