### ISSUE TITLE
Support Material Update

### ISSUE THREAD

**Issue by maxwxyz** [jaheyns/CfdOF#165]
Adding an CfdOF Analysis container results in a lot of errors with importing material. I'd guess because of the recent changes (still ongoing) to the material system of FreeCAD.

**Comment by oliveroxtoby** [comment]
There is a fix in the works, should appear soon in FreeCAD - see https://forum.freecad.org/viewtopic.php?t=86659

**Comment by oliveroxtoby** [comment]
I think this is resolved now. Please feel free to re-open if not.
