### ISSUE TITLE
Fluid Properties - Compressible Checkbox

### ISSUE THREAD

**Issue by seawasp2** [jaheyns/CfdOF#169]
Not sure if the Compressible checkbox in the Fluid Properties panel behaves correctly, but this might be a newbie issue. Repeated checking and unchecking of the Compressible checkbox gives different input boxes. 
In the Physics model, non-isothermal and RANS selected

When you go to the Fluid Properties Panel, the Compressible checkbox is ticked and Air is selected.
Below it lists: Molar Mass, Cp, Sutherland Temperature, Sutherland Ref Temperature, Sutherland Ref Viscosity.

Uncheck Compressibility and water is selected
Below it lists: Molar Mass, DensityPolynomial, CpPolynomial, DynamicViscosityPolynomial, ThermalConductivityPolynomial

Check Compressibility and water is selected
Below it lists: Molar Mass, Cp

Uncheck Compressibility and water is selected
Below it lists nothing

Check Compressibility and water is selected
Below it lists nothing 

Uncheck Compressibility and water is selected
Below it lists: Molar Mass, DensityPolynomial, CpPolynomial, DynamicViscosityPolynomial, ThermalConductivityPolynomial

Check Compressibility and water is selected
Below it lists nothing

Uncheck Compressibility and water is selected
Below it lists: Molar Mass, DensityPolynomial, CpPolynomial, DynamicViscosityPolynomial, ThermalConductivityPolynomial

Check Compressibility and water is selected
Below it lists Molar Mass <------ That's a new one

Uncheck Compressibility and water is selected
Below it lists nothing

Check Compressibility and water is selected
Below it lists nothing

[code]
OS: Ubuntu 22.04.4 LTS (ubuntu:GNOME/ubuntu-xorg)
Word size of FreeCAD: 64-bit
Version: 0.21.1.33694 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 0.21.1)
Hash: f6708547a9bb3f71a4aaade12109f511a72c207c
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: English/United Kingdom (en_GB)
Installed mods: 
  * CfdOF 1.25.12
  * Plot 2022.4.17
[/code]

**Comment by oliveroxtoby** [comment]
Thanks. That was defninitely a bug. Should be working now.
