### ISSUE TITLE
Errors with Running the Solver

### ISSUE THREAD

**Issue by RaysKindaCrazy** [jaheyns/CfdOF#174]
I have CfdOF v1.25.17 , OpenFOAM 11 v2212 , and running a mesh with cfMesh

I have double checked the directories, and have reinstalled incase that is the problem. But when I run the solver and re-mesh case I get the error

![Screenshot 2024-06-19 121101](https://github.com/jaheyns/CfdOF/assets/173292911/9236c5af-e539-45e5-822e-13eac2f7fdf4)

When I run without re-meshing the case it says

![Screenshot 2024-06-19 121039](https://github.com/jaheyns/CfdOF/assets/173292911/5292f767-6b4d-46e1-badf-ffa72e3e7b4d)

I dont see how to fix the issue, without editing the software, and I have not seen anyone post about this. If anyone has any suggestions of what I might've missed I'd love to hear since I've tried all I know

**Comment by oliveroxtoby** [comment]
This seems more likely to be a support query than a bug report. Please post on the forum at https://forum.freecad.org/viewforum.php?f=37, making sure to include your FreeCAD file so that other users can attempt to reproduce your issue.

**Comment by RaysKindaCrazy** [comment]
Yes, sorry and thank you

**Comment by oliveroxtoby** [comment]
@RaysKindaCrazy FYI this should be resolved now
