### ISSUE TITLE
Bug reporting - 'Needs Mesh Rewrite' is being set to true with "Clear" or "Load surface Mesh" click

### ISSUE THREAD

**Issue by mas985** [jaheyns/CfdOF#184]
'Needs Mesh Rewrite' is being set to true when I don't think it should be.

Post mesh creation and either "Clear" is pressed or "Load surface mesh" is pressed. Both seem to change 'Needs Mesh Rewrite' from false to true.

This creates an issue when running the solver as it will ask to run the mesh again even when it was just run.

How to repeat:

CFD Mesh panel
Click 'Clear'
Click ' Write mesh case'
Click 'Run mesher'
Click 'Load surface mesh'

Look at  'Needs Mesh Rewrite' in CfdAnalysis data properties - should be false but is true

Set 'Needs Mesh Rewrite' back to false
CFD Mesh Panel
Click 'Clear'

Look at  'Needs Mesh Rewrite' in CfdAnalysis data properties - should be false but is true

```
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git)
Build type: Release
Branch: releases/FreeCAD-0-21
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * CfdOF 1.27.8
  * Help 1.0.3
```

**Comment by oliveroxtoby** [comment]
Appreciate you tracking down the cause of this. Should be resolved now.

**Comment by mas985** [comment]
Thanks!
