### ISSUE TITLE
FreeCAD 0.18 ?

### ISSUE THREAD

**Issue by joseRey** [jaheyns/CfdOF#19]
I just noticed Freecad 0.18 was released. I love the CfdOF addon and thank you very much for making it possible.  Will it be updated for Freecad 0.18 ?  Thanks

**Comment by oliveroxtoby** [comment]
Thank you. It is working on 0.18, although there are some dependency issues with the AppImage in Linux which we are trying to sort out. Are you experiencing a specific problem?

**Comment by joseRey** [comment]
Not really, I just did not know if it was updated for version 0.18, and didn't want to install it until CfdOF was available :)  Thank you very much
