### ISSUE TITLE
CfdOF - Please create SVG logo for this workbench

### ISSUE THREAD

**Issue by luzpaz** [jaheyns/CfdOF#21]
It will be added to the new and improved Addon Manager  
https://github.com/FreeCAD/FreeCAD-addons/issues/37

**Comment by oliveroxtoby** [comment]
Done, in Gui/Resources/icons/cfd.svg. Don't know if this needs to go into the FreeCAD source or just be reference by the icon= in the metadata?

**Comment by luzpaz** [comment]
Sweet! You could reference this in the metadata. I'll grab it now and add it to the PR I'm working on at https://github.com/FreeCAD/FreeCAD/pull/2261
Thanks!
