### ISSUE TITLE
AttributeError: module 'Plot' has no attribute 'figure'

### ISSUE THREAD

**Issue by fb-multimedia** [jaheyns/CfdOF#25]
Case write is ok but when I'm running the solver I got this error :
`Start to write case to folder /tmp
Matching boundary conditions ...
Populating createPatchDict to update BC names
Successfully wrote case to folder /tmp
Traceback (most recent call last):
  File "/home/fred/.FreeCAD/Mod/CfdOF/_TaskPanelCfdSolverControl.py", line 152, in runSolverProcess
    cmd = self.solver_runner.get_solver_cmd(solverDirectory)
  File "/home/fred/.FreeCAD/Mod/CfdOF/CfdRunnableFoam.py", line 93, in get_solver_cmd
    self.residualPlot = ResidualPlot()
  File "/home/fred/.FreeCAD/Mod/CfdOF/CfdResidualPlot.py", line 37, in __init__
    self.fig = Plot.figure(FreeCAD.ActiveDocument.Name + "Residuals")
AttributeError: module 'Plot' has no attribute 'figure'`

the same error has been reported here :
https://forum.freecadweb.org/viewtopic.php?f=3&t=37553

When following this plot workbench basic tutorial :
https://www.freecadweb.org/wiki/Plot_Basic_tutorial

I've the same error in the console after this two command :
`import Plot`
`Plot.figure("TrigonometricTest")`
`Traceback (most recent call last):
  File "<input>", line 1, in <module>
AttributeError: module 'Plot' has no attribute 'figure'`

So I post this same issue on freecad.plot repo.
https://github.com/FreeCAD/freecad.plot/issues/8

Hope somebody can help...

config : 
Ubuntu 18.04
Freecad   0.18.3
Python 3.6.8

**Comment by oliveroxtoby** [comment]
I can't reproduce this on my (non-Ubuntu) system. I am wondering: did you install the Plot module through Tools | Modules or does it come packaged with FreeCAD when you install the ppa?

**Comment by fb-multimedia** [comment]
Thanks for your help
I've install it with tools/modules

**Comment by fb-multimedia** [comment]
Installing freecad v0.19 solve the issue. It's work now !
Thanks for your help
