### ISSUE TITLE
FOAM FATAL when mesh is generated

### ISSUE THREAD

**Issue by msebas** [jaheyns/CfdOF#26]
Hi,

I am using freecad 0.18 on openSUSE Leap 15.0 (from the repository science version 0.18.3-lp150.97.1) and openfoam version 1906-lp150.6.1.

I am trying the [tutorial 1](https://github.com/opensimsa/opensim/raw/master/Documentation/CFD/Elbow/CFD%20Tutorial%201%20-%20Elbow.pdf) and when I try to create the mesh (page 14) I got the message "3.9: Meshing exited with error".

Looking into the output lead me to a "FOAM FATAL
surfaceMeshTriangulate has been superceded by surfaceMeshExtract (DEC-2018)" at the end of the log output. Substituting "runCommand surfaceMeshTriangulate mesh_outside.stl" by "runCommand surfaceMeshExtract mesh_outside.stl" in the Allmesh script resolved the issue.

Please excuse, but I do not know where to look to fix it without introducing additional trouble.

Kind regards 

Full LOG:
Part to mesh:
  Name: Body, Label: Body, ShapeType: Solid
  CharacteristicLengthMax: 800.0
  ElementDimension: 3D
  No mesh refinements
Populating mesh dictionaries in folder /tmp/freecad/meshCase
Successfully wrote meshCase to folder /tmp/freecad/meshCase
Executing: bash -c cd "/tmp/freecad/meshCase" && ./Allmesh
Raw command:  ['bash', '-c', 'cd "/tmp/freecad/meshCase" && ./Allmesh']
Info    : Running '/usr/bin/gmsh - gmsh/Body_Geometry.geo' [Gmsh 4.4.1, 1 node, max. 1 thread]
Info    : Started on Wed Oct 16 16:24:47 2019
Info    : Reading 'gmsh/Body_Geometry.geo'...
Info    : Reading '/tmp/freecad/meshCase/gmsh/Body_Geometry.brep'...
Info    : Done reading '/tmp/freecad/meshCase/gmsh/Body_Geometry.brep'
Info    : Meshing 1D...
Info    : Meshing curve 1 (Line)
Info    : Meshing curve 2 (Line)
Info    : Meshing curve 3 (Line)
Info    : Meshing curve 4 (Line)
Info    : Meshing curve 5 (Line)
Info    : Meshing curve 6 (Line)
Info    : Meshing curve 7 (Line)
Info    : Meshing curve 8 (Line)
Info    : Meshing curve 9 (Line)
Info    : Meshing curve 10 (Line)
Info    : Meshing curve 11 (Line)
Info    : Meshing curve 12 (Circle)
Info    : Meshing curve 13 (Circle)
Info    : Meshing curve 14 (Line)
Info    : Meshing curve 15 (Line)
Info    : Meshing curve 16 (Line)
Info    : Meshing curve 17 (Line)
Info    : Meshing curve 18 (Line)
Info    : Meshing curve 19 (Line)
Info    : Meshing curve 20 (Line)
Info    : Meshing curve 21 (Line)
Info    : Meshing curve 22 (Line)
Info    : Meshing curve 23 (Line)
Info    : Meshing curve 24 (Circle)
Info    : Meshing curve 25 (Circle)
Info    : Meshing curve 26 (Line)
Info    : Meshing curve 27 (Line)
Info    : Meshing curve 28 (Line)
Info    : Meshing curve 29 (Line)
Info    : Meshing curve 30 (Line)
Info    : Meshing curve 31 (Line)
Info    : Meshing curve 32 (Line)
Info    : Meshing curve 33 (Line)
Info    : Meshing curve 34 (Line)
Info    : Meshing curve 35 (Circle)
Info    : Meshing curve 36 (Circle)
Info    : Done meshing 1D (0.006575 s)
Info    : Meshing 2D...
Info    : Meshing surface 1 (Plane, Delaunay)
Info    : Meshing surface 2 (Plane, Delaunay)
Info    : Meshing surface 3 (Plane, Delaunay)
Info    : Meshing surface 4 (Cylinder, Delaunay)
Info    : Meshing surface 5 (Plane, Delaunay)
Info    : Meshing surface 6 (Plane, Delaunay)
Info    : Meshing surface 7 (Plane, Delaunay)
Info    : Meshing surface 8 (Cylinder, Delaunay)
Info    : Meshing surface 9 (Plane, Delaunay)
Info    : Meshing surface 10 (Plane, Delaunay)
Info    : Meshing surface 11 (Plane, Delaunay)
Info    : Meshing surface 12 (Cylinder, Delaunay)
Info    : Meshing surface 13 (Plane, Delaunay)
Info    : Meshing surface 14 (Plane, Delaunay)
Info    : Done meshing 2D (0.872024 s)
Info    : Meshing 3D...
Info    : 3D Meshing 1 volumes with 1 connected components
Info    : Tetrahedrization of 7532 points in 0.161071 seconds
Info    : Reconstructing mesh...
Info    :  - Creating surface mesh
Info    :  - Identifying boundary edges
Info    :  - Recovering boundary
Info    :  - Added 18 Steiner points
Info    : Done reconstructing mesh (0.481506 s)
Info    : Found region 1
Info    : 0 points created - worst tet radius 1.64878 (points removed 0 0)
Info    : 3D point insertion terminated (7574 points created):
Info    :  - 0 Delaunay cavities modified for star shapeness
Info    :  - 42 points could not be inserted
Info    :  - 22562 tetrahedra created in 0.005953 sec. (3790021 tets/s)
Info    : Done meshing 3D (0.729099 s)
Info    : Optimizing 3D mesh...
Info    : Optimizing volume 1
Info    : Optimization starts (volume = 1.68261e+12) with worst = 0.0109476 / average = 0.70175:
Info    : 0.00 < quality < 0.10 :       217 elements
Info    : 0.10 < quality < 0.20 :       160 elements
Info    : 0.20 < quality < 0.30 :       141 elements
Info    : 0.30 < quality < 0.40 :       166 elements
Info    : 0.40 < quality < 0.50 :       301 elements
Info    : 0.50 < quality < 0.60 :      1556 elements
Info    : 0.60 < quality < 0.70 :      6350 elements
Info    : 0.70 < quality < 0.80 :     10825 elements
Info    : 0.80 < quality < 0.90 :      2263 elements
Info    : 0.90 < quality < 1.00 :       583 elements
Info    : 500 edge swaps, 4 node relocations (volume = 1.68261e+12): worst = 0.0134277 / average = 0.714694 (0.015967 s)
Info    : 525 edge swaps, 5 node relocations (volume = 1.68261e+12): worst = 0.0134277 / average = 0.715034 (0.020887 s)
Info    : 4 ill-shaped tets are still in the mesh
Info    : 0.00 < quality < 0.10 :         9 elements
Info    : 0.10 < quality < 0.20 :         9 elements
Info    : 0.20 < quality < 0.30 :         5 elements
Info    : 0.30 < quality < 0.40 :       157 elements
Info    : 0.40 < quality < 0.50 :       266 elements
Info    : 0.50 < quality < 0.60 :      1424 elements
Info    : 0.60 < quality < 0.70 :      6487 elements
Info    : 0.70 < quality < 0.80 :     10955 elements
Info    : 0.80 < quality < 0.90 :      2212 elements
Info    : 0.90 < quality < 1.00 :       578 elements
Info    : Done optimizing 3D mesh (0.049231 s)
Info    : 7574 vertices 37873 elements
Info    : Writing '/tmp/freecad/meshCase/gmsh/Body_Geometry.msh'...
Info    : Done writing '/tmp/freecad/meshCase/gmsh/Body_Geometry.msh'
Info    : Done reading 'gmsh/Body_Geometry.geo'
Info    : Stopped on Wed Oct 16 16:24:49 2019
/*---------------------------------------------------------------------------*\
| =========                 |                                                 |
| \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
|  \\    /   O peration     | Version:  1906                                  |
|   \\  /    A nd           | Web:      www.OpenFOAM.com                      |
|    \\/     M anipulation  |                                                 |
\*---------------------------------------------------------------------------*/
Build  : 1906 OPENFOAM=1906 patch=191001
Arch   : "LSB;label=32;scalar=64"
Exec   : gmshToFoam gmsh/Body_Geometry.msh
Date   : Oct 16 2019
Time   : 16:24:50
Host   : lukas
PID    : 17806
I/O    : uncollated
Case   : /tmp/freecad/meshCase
nProcs : 1
trapFpe: Floating point exception trapping enabled (FOAM_SIGFPE).
fileModificationChecking : Monitoring run-time modified files using timeStampMaster (fileModificationSkew 10)
allowSystemOperations : Allowing user-supplied system call operations

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //
Create time

--> FOAM Warning : 
    From function static Foam::IOstreamOption::compressionType Foam::IOstreamOption::compressionEnum(const Foam::word&)
    in file db/IOstreams/IOstreams/IOstreamOption.C at line 86
    Unknown compression specifier 'uncompressed', assuming no compression
Starting to read mesh format at line 2
Read format version 2.2  ascii 0

Starting to read physical names at line 5
Physical names:15
    Surface 2	face0
    Surface 3	face1
    Surface 4	face2
    Surface 5	face3
    Surface 6	face4
    Surface 7	face5
    Surface 8	face6
    Surface 9	face7
    Surface 10	face8
    Surface 11	face9
    Surface 12	face10
    Surface 13	face11
    Surface 14	face12
    Surface 15	face13
    Volume 1	Internal

Starting to read points at line 23
Vertices to be read: 7574
Vertices read:7574

Starting to read cells at line 7600
Cells to be read: 37169

Mapping region 2 to Foam patch 0
Mapping region 3 to Foam patch 1
Mapping region 4 to Foam patch 2
Mapping region 5 to Foam patch 3
Mapping region 6 to Foam patch 4
Mapping region 7 to Foam patch 5
Mapping region 8 to Foam patch 6
Mapping region 9 to Foam patch 7
Mapping region 10 to Foam patch 8
Mapping region 11 to Foam patch 9
Mapping region 12 to Foam patch 10
Mapping region 13 to Foam patch 11
Mapping region 14 to Foam patch 12
Mapping region 15 to Foam patch 13
Mapping region 1 to Foam cellZone 0
Cells:
    total:22125
    hex  :0
    prism:0
    pyr  :0
    tet  :22125

CellZones:
Zone	Size
    0	22125

Patch 0 gets name face0
Patch 1 gets name face1
Patch 2 gets name face2
Patch 3 gets name face3
Patch 4 gets name face4
Patch 5 gets name face5
Patch 6 gets name face6
Patch 7 gets name face7
Patch 8 gets name face8
Patch 9 gets name face9
Patch 10 gets name face10
Patch 11 gets name face11
Patch 12 gets name face12
Patch 13 gets name face13

--> FOAM Warning : 
    From function Foam::polyMesh::polyMesh(const Foam::IOobject&, Foam::pointField&&, const cellShapeList&, const faceListList&, const wordList&, const wordList&, const Foam::word&, const Foam::word&, const wordList&, bool)
    in file meshes/polyMesh/polyMeshFromShapeMesh.C at line 592
    Found 15044 undefined faces in mesh; adding to default patch.
Finding faces of patch 0
Finding faces of patch 1
Finding faces of patch 2
Finding faces of patch 3
Finding faces of patch 4
Finding faces of patch 5
Finding faces of patch 6
Finding faces of patch 7
Finding faces of patch 8
Finding faces of patch 9
Finding faces of patch 10
Finding faces of patch 11
Finding faces of patch 12
Finding faces of patch 13

FaceZones:
Zone	Size

Writing zone 0 to cellZone Internal and cellSet
End

/*---------------------------------------------------------------------------*\
| =========                 |                                                 |
| \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
|  \\    /   O peration     | Version:  1906                                  |
|   \\  /    A nd           | Web:      www.OpenFOAM.com                      |
|    \\/     M anipulation  |                                                 |
\*---------------------------------------------------------------------------*/
Build  : 1906 OPENFOAM=1906 patch=191001
Arch   : "LSB;label=32;scalar=64"
Exec   : transformPoints -scale (0.001 0.001 0.001)
Date   : Oct 16 2019
Time   : 16:24:51
Host   : lukas
PID    : 17812
I/O    : uncollated
Case   : /tmp/freecad/meshCase
nProcs : 1
trapFpe: Floating point exception trapping enabled (FOAM_SIGFPE).
fileModificationChecking : Monitoring run-time modified files using timeStampMaster (fileModificationSkew 10)
allowSystemOperations : Allowing user-supplied system call operations

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //
Create time

--> FOAM Warning : 
    From function static Foam::IOstreamOption::compressionType Foam::IOstreamOption::compressionEnum(const Foam::word&)
    in file db/IOstreams/IOstreams/IOstreamOption.C at line 86
    Unknown compression specifier 'uncompressed', assuming no compression
Scaling points by (0.001 0.001 0.001)
Writing points into directory "/tmp/freecad/meshCase/constant/polyMesh"

End

FOAM FATAL
surfaceMeshTriangulate has been superceded by surfaceMeshExtract (DEC-2018)

**Comment by oliveroxtoby** [comment]
Thanks for reporting.

**Comment by msebas** [comment]
Thanks for  the fix.

**Comment by bternity** [comment]
Brother, I also encountered this problem. 
Has your problem been solved?
