### ISSUE TITLE
Error when using PartDesign Boolean

### ISSUE THREAD

**Issue by adrianinsaval** [jaheyns/CfdOF#27]
https://github.com/jaheyns/CfdOF/blob/8691c5eaa0c32e94f485e3acadf4fd65b0b608ec/CfdTools.py#L242

Hi, this implementation is problematic because it trows errors when there is a PartDesign Boolean (wich doesn't have the Mode property) in the document, a workaround is to manually create a Mode property in the boolean feature.

Here the error:
`Traceback (most recent call last):
  File "C:\Users\usuario\AppData\Roaming\FreeCAD\Mod\CfdOF\CfdMesh.py", line 155, in onChanged
    CfdTools.setCompSolid(vobj)
  File "C:\Users\usuario\AppData\Roaming\FreeCAD\Mod\CfdOF\CfdTools.py", line 241, in setCompSolid
    FreeCAD.getDocument(doc_name).getObject(obj.Name).Mode = 'CompSolid'
<class 'AttributeError'>: 'PartDesign.Feature' object has no attribute 'Mode'
`

And my FreeCAD info in case it's relevant:
> OS: Windows 10 (10.0)
> Word size of OS: 64-bit
> Word size of FreeCAD: 64-bit
> Version: 0.19.18750 (Git)
> Build type: Release
> Branch: master
> Hash: a3e88a399fb6395a20f4cf5c7e3ed70e61c9e22f
> Python version: 3.7.3
> Qt version: 5.12.1
> Coin version: 4.0.0a
> OCC version: 7.3.0
> Locale: Spanish/Paraguay (es_PY)

[example.zip](https://github.com/jaheyns/CfdOF/files/3935506/example.zip)
Attached a minimal example (change zip to FCStd), double click Sphere_Mesh to get the error

**Comment by oliveroxtoby** [comment]
Thank you for reporting. This should be rectified.
