### ISSUE TITLE
Hisa don't work at OpenFoam 7 

### ISSUE THREAD

**Issue by ChrisDarquea** [jaheyns/CfdOF#28]
Greetings.
I have a problem when I try to use CFD for freecad, I believe that is something similar to the error that ca be find in these link: https://github.com/jaheyns/CfdOF/issues/12 
But the difference is that I am using OpenFoam 7, you could help me. 
 
![Attemt to install hisa two](https://user-images.githubusercontent.com/58714023/70877796-01d7ef80-1f8d-11ea-8510-78fa9ba7ae45.png)

**Comment by oliveroxtoby** [comment]
HiSA has been updated - this should be resolved if you reinstall HiSA from the preference page. Thanks for reporting.

**Comment by ChrisDarquea** [comment]
Thanks very much, it is working
