### ISSUE TITLE
Add LGTM badge

### ISSUE THREAD

**Issue by luzpaz** [jaheyns/CfdOF#30]
Per https://github.com/FreeCAD/FreeCAD-addons/issues/163

Would it be OK if we added these badges to the top of the README ? This was discussed in https://www.forum.freecadweb.org/viewtopic.php?f=10&t=40228  

```
[![Total alerts](https://img.shields.io/lgtm/alerts/g/jaheyns/CfdOF.svg?logo=lgtm&logoWidth=18)](https://lgtm.com/projects/g/jaheyns/CfdOF/alerts/)
```  
Example: [![Total alerts](https://img.shields.io/lgtm/alerts/g/jaheyns/CfdOF.svg?logo=lgtm&logoWidth=18)](https://lgtm.com/projects/g/jaheyns/CfdOF/alerts/)

```
[![Language grade: Python](https://img.shields.io/lgtm/grade/python/g/jaheyns/CfdOF.svg?logo=lgtm&logoWidth=18)](https://lgtm.com/projects/g/jaheyns/CfdOF/context:python)
```  
Example: [![Language grade: Python](https://img.shields.io/lgtm/grade/python/g/jaheyns/CfdOF.svg?logo=lgtm&logoWidth=18)](https://lgtm.com/projects/g/jaheyns/CfdOF/context:python)

**Comment by oliveroxtoby** [comment]
Thanks!
