### ISSUE TITLE
blueCFD automatic download fails to launch installer

### ISSUE THREAD

**Issue by alafr** [jaheyns/CfdOF#31]
Hi,
If i click install blueCFD-core in the preferences dialog, it downloads a file with no extension instead of .exe and it fails to launch the installer
![image](https://user-images.githubusercontent.com/17966696/77625413-d11c3480-6f43-11ea-93bc-c4f8942eaeb5.png)
![image](https://user-images.githubusercontent.com/17966696/77627444-36bdf000-6f47-11ea-902d-892f5819cd28.png)
Translation: There is no association of an application with the specified file for this operation
![image](https://user-images.githubusercontent.com/17966696/77627500-4dfcdd80-6f47-11ea-80ec-fc3092ba5de0.png)
![image](https://user-images.githubusercontent.com/17966696/77627654-82709980-6f47-11ea-818e-7ce1112419a5.png)

If i download the file by copying the given url https://github.com/blueCFD/Core/releases/download/blueCFD-Core-2017-2/blueCFD-Core-2017-2-win64-setup.exe in the browser, and then select it with choose existing file, it works fine.

**Comment by oliveroxtoby** [comment]
Thanks for reporting. Should be fixed.

**Comment by alafr** [comment]
Yes it's fixed. Thanks!
