### ISSUE TITLE
Hisa not found after install completed

### ISSUE THREAD

**Issue by Estay1991** [jaheyns/CfdOF#35]
I am new to freeCAD. Just installed it today, but there is a problem with Hisa. It always says Hisa is not found after install complete.
![image](https://user-images.githubusercontent.com/67368889/85537715-06651b00-b636-11ea-8d58-1158caf45961.png)

**Comment by Estay1991** [comment]
@oliveroxtoby

**Comment by Estay1991** [comment]
@Titi9237, please help

**Comment by Estay1991** [comment]
@oliveroxtoby

**Comment by Estay1991** [comment]
![image](https://user-images.githubusercontent.com/67368889/85547141-67452100-b63f-11ea-9529-1586bc383ada.png)

**Comment by oliveroxtoby** [comment]
Please could you read https://forum.freecadweb.org/viewtopic.php?f=37&t=33492&sid=3f65758ad69376c655edcaddf5d5bf0d and provide the information requested, particularly the version information from FreeCAD.

**Comment by bakakouhai** [comment]
Hello @oliveroxtoby.

Since I cannot find the solution for meshing problem in 20.04 before, I want to try it in 18.04.
I encounter this problem also.

The system is running in Virtualbox.
Pop_OS 18.04
FreeCAD 18.4 installed via synaptic.
OpenFOAM 4.x with HELYX-OS

The report log is attached:
[hisa.log](https://github.com/jaheyns/CfdOF/files/4874566/hisa.log)

Kind regards,
Iwan

**Comment by oliveroxtoby** [comment]
I have been able to reproduce this - for some reason BlueCFD commands are not running properly in certain versions of FreeCAD. I can't figure out what the issue is but I have now switched the default Windows installation to the OpenCFD Docker package. This seems to resolve the problem.

**Comment by oliveroxtoby** [comment]
> Hello @oliveroxtoby.
> 
> Since I cannot find the solution for meshing problem in 20.04 before, I want to try it in 18.04.
> I encounter this problem also.
> 
> The system is running in Virtualbox.
> Pop_OS 18.04
> FreeCAD 18.4 installed via synaptic.
> OpenFOAM 4.x with HELYX-OS
> 
> The report log is attached:
> [hisa.log](https://github.com/jaheyns/CfdOF/files/4874566/hisa.log)
> 
> Kind regards,
> Iwan

This is a different issue to the one above, but I will look into it. For now I suggest using a new version of OpenFOAM - this seems to be an issue compiling HiSA in OpenFOAM v4.
