### ISSUE TITLE
Allrun FOAMDIR= set wrong

### ISSUE THREAD

**Issue by TimScottz8** [jaheyns/CfdOF#39]
I'm running FreeCAD 0.18.4 on Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic

I've installed CfdOF successfully and the dependency check is OK. Under the freecad preferences CfdOF the OpenFoam install directory is set to /opt/openfoam6. Meshing works absolutely fine. When I go to the Solver module and write the case out it sets the Allrun FOAMDIR="None" everytime. The work around is just to edit the Allrun in kate and set the FOAMDIR="/opt/openfoam6" and all is well but it would be nice not to have to and will probably confuse new users. It took me a while to figure out the problem being new to OpenFoam

**Comment by oliveroxtoby** [comment]
I have not had any success trying to reproduce this and can't figure out why it would be OK in the mesh case and not the solver one. I have added a few lines of debugging output that gets written to the Report view when the dependency check is run. If you could update CfdOF, re-run the dependency check and send the entire output of the report view, this may help to give some clue. See here for info about the report view: https://forum.freecadweb.org/viewtopic.php?f=37&t=33492

**Comment by TimScottz8** [comment]
I'll try and reproduce it later this evening Thanks for the quick replyTim Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Oliver Oxtoby <notifications@github.com> Date: 15/08/2020  20:49  (GMT+00:00) To: jaheyns/CfdOF <CfdOF@noreply.github.com> Cc: TimScottz8 <Tim@trscott.me.uk>, Author <author@noreply.github.com> Subject: Re: [jaheyns/CfdOF] Allrun FOAMDIR= set wrong (#39) 
I have not had any success trying to reproduce this and can't figure out why it would be OK in the mesh case and not the solver one. I have added a few lines of debugging output that gets written to the Report view when the dependency check is run. If you could update CfdOF, re-run the dependency check and send the entire output of the report view, this may help to give some clue. See here for info about the report view: https://forum.freecadweb.org/viewtopic.php?f=37&t=33492

**Comment by TimScottz8** [comment]
I tried to reproduce the issue last night after re-installing CfdOF and couldn't. So it seems that reinstalling solved the problem :) . For anyone else who has the problem then the workaround is simple. Just manually insert the path to openfoam in the AllRun file.
Thanks for the help
