### ISSUE TITLE
Problems with cfMesh and HiSA

### ISSUE THREAD

**Issue by AlanEstrada14** [jaheyns/CfdOF#41]
Hello, I have the same problem with cfMesh and HiSA, I do not know what is the problem, can you help me please? 

![Captura de pantalla 2020-09-04 a la(s) 12 00 17](https://user-images.githubusercontent.com/70770604/92267390-3d617380-eea6-11ea-888d-56170601cb74.png)

**Comment by oliveroxtoby** [comment]
Please have a look at the forum: https://forum.freecadweb.org/viewforum.php?f=37
You may be able to get assistance there.
