### ISSUE TITLE
UAV case slicemesh meshrefinement Err

### ISSUE THREAD

**Issue by skunk69** [jaheyns/CfdOF#43]
11:12:00  Traceback (most recent call last):
  File "C:\Users\...\AppData\Roaming\FreeCAD\Mod\cfdOF\CfdMeshRefinement.py", line 133, in execute
    obj.Shape = shape
<class 'AttributeError'>: 'FeaturePython' object has no attribute 'Shape'

**Comment by oliveroxtoby** [comment]
I think you may be editing a file that was created prior to a recent update of the workbench, which has broken backward compatibility of the mesh refinement objects. Please could you try removing and re-adding any mesh refinement objects?

If not, please provide a saved files and instructions on reproducing this error.

**Comment by skunk69** [comment]
yes，I will try again

**Comment by skunk69** [comment]
It's done, You helped. Thank you!
