### ISSUE TITLE
Support XDG Base Directory Specification

### ISSUE THREAD

**Issue by einhander** [jaheyns/CfdOF#46]
Installation script of cfMesh and HiSA violates XDG Base Directory Specification.
Right now installation path is like this $HOME/OpenFOAM/$USER-v$VERSION/platforms/$OSarch$Gccversion/ that contains bin and lib directories. (In my case $HOME/OpenFOAM/einhander-v2012/platforms/linux64GccDPInt32Opt)
By XDG Specification bin and lib should be located under $HOME/.local/ directory. 
But in case of multiple version software like OpenFOAM, I think that cfMesh bin and lib should be placed under  $HOME/.local/lib/openfoam/openfoam2012/platforms/linux64GccDPInt32Opt/ like it placed in /usr/ directory in openfoam2012 binary package.

XDG specification with examples https://wiki.archlinux.org/index.php/XDG_Base_Directory

**Comment by oliveroxtoby** [comment]
CfdOF simply uses the standard OpenFOAM user directories here (see the environment variables FOAM_USER_APPBIN, FOAM_USER_LIBBIN, etc), so I think this is an issue to be addressed with them.
