### ISSUE TITLE
Preference Page is not working

### ISSUE THREAD

**Issue by jadye21** [jaheyns/CfdOF#47]
![Screenshot from 2021-02-27 19-12-34](https://user-images.githubusercontent.com/79545851/109404040-1dc87680-7930-11eb-9da2-16d5daf43935.png)

When trying to access the CfdOF Preference page it came up blank, and at the bottom in yellow lettering it says, "Cfd Preference Page is not a preference page"

**Comment by oliveroxtoby** [comment]
I'm not able to reproduce this issue. Please could you provide your version information - go to Help | About, and click "Copy to clipboard".

Which installation are you using - the system package manager's, AppImage, etc...?

**Comment by jadye21** [comment]
The version information is - version 0.18 build 16093 +53 (Git)
I installed using the Ubuntu Software app.
Thanks for your help.

**Comment by oliveroxtoby** [comment]
It seems that there are some issues using this with git versions less than 16146.

Please have a look at the Readme for options of installing a newer version - I would suggest the 0.19 prerelease as this is about to become the stable version.

**Comment by adityahiyer** [comment]
I'm having the same issue now - I tried to post about it on the forum, but I think my post wasn't approved. I'm also getting some errors regarding the CfdTools and CfdPreferencePage Python files. 

My installation details are: 
OS: Windows 11 build 26100
Architecture: x86_64
Version: 1.0.2.39319 (Git) Conda
Build type: Release
Branch: (HEAD detached at 1.0.2)
Hash: 256fc7eff3379911ab5daf88e10182c509aa8052
Python 3.11.13, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: English/India (en_IN)
Stylesheet/Theme/QtStyle: FreeCAD Light.qss/FreeCAD Light/Fusion
Installed mods: 
  * AddonManager 2025.8.16
  * CfdOF 1.31.7



Not sure how to fix this.

**Comment by oliveroxtoby** [comment]
Sorry, this was a bug. Should be fixed now.
