### ISSUE TITLE
Load issue - missing dependencies

### ISSUE THREAD

**Issue by mdziczkowski** [jaheyns/CfdOF#49]
While attempting to load the CfdOF, I get following error message:

`During initialization the error "module 'CfdTools' has no attribute 'get_module_path'" occurred in share/Mod/CfdOF/InitGui.py
`

Note: For security reasons, the patch was truncated

### System:

* Debian 10 (64-bit) - Linux
* FreeCAD version: 4.0.0

**Comment by oliveroxtoby** [comment]
I'm unable to reproduce this issue unfortunately. Perhaps some of the information at https://forum.freecadweb.org/viewtopic.php?f=37&t=33492 will help.
