### ISSUE TITLE
HiSA and cfMesh install issues

### ISSUE THREAD

**Issue by AaronDinesh** [jaheyns/CfdOF#54]
Hi I'm running windows 10 and I was trying to install cdfof on freecad. I used the buttons in the preferences panel to install all the dependencies. I put OpenFoam in a folder on my desktop and it's my understanding that HiSA and cfMesh are installed to the OpenFoam folder? But whenever I hit install it just installs the Zip file to the Temp directory. When running the dependency checker it takes a long time and then says that it couldn't find the HiSA or cfMesh install. Is there something I'm doing wrong? The OpenFoam folder on my desktop should be writeable

**Comment by oliveroxtoby** [comment]
The zip file is downloaded to the temp folder but after that the files are supposed to be copied to the OpenFOAM folder. As a check, see if the file hisa.exe is present in the folder: <OpenFOAM install folder>\OpenFOAM\v2012\msys64\home\ofuser\OpenFOAM\OpenFOAM-v2012\platforms\win64MingwDPInt32Opt\bin
On my machine, <OpenFOAM install folder> is C:\Program Files\ESI-OpenCFD

Providing the full output of the report view during the installation and dependency checking might give some clues to the problem. Please see https://forum.freecadweb.org/viewtopic.php?f=37&t=33492&sid=46ecce67e64dd844c01caa3334ee7cf5 for more tips.

**Comment by keugbang** [comment]
Not sure but the long path name might be the culprit.
I have moved the installed OpenFOAM folder from 

- `E:\FreeCAD\cfdOF\Dependencies\OpenFOAM` 

which failed to recognize cfMesh/HiSA installation, to

- `E:\OpenFOAM`

and the dependency checker succeeds.
