### ISSUE TITLE
Allmesh row 26 and 41

### ISSUE THREAD

**Issue by demonlibra** [jaheyns/CfdOF#57]
file Allmesh
row 26 and 41
`if [ -z $FOAM_API ] && [ $WM_PROJECT_VERSION -ge 9 ]`

But version can be not only with digits.
I installed openfoam from https://openfoam.org/download/dev-ubuntu/ and get version "dev".

**Comment by luzpaz** [comment]
@demonlibra you can click on the line number(s) like so:

https://github.com/jaheyns/CfdOF/blob/master/data/defaultsMesh/Allmesh#L25-L29

**Comment by demonlibra** [comment]
https://github.com/jaheyns/CfdOF/blob/6795093e85938a23023832b3b9b324b592750b6b/data/defaultsMesh/Allmesh#L75

**Comment by oliveroxtoby** [comment]
Thanks for reporting. Hopefully it will be working now.

**Comment by demonlibra** [comment]
Checked. Working fine.
Thank you.
