### ISSUE TITLE
errors from excuting FCMACRO

### ISSUE THREAD

**Issue by skunk69** [jaheyns/CfdOF#60]
the solver cannot run when I excute the FCMACRO file. The errors are:

10:14:15  Exception ignored in: <function CfdConsoleProcess.__del__ at 0x000001AE939E6E50>
10:14:15  Traceback (most recent call last):
10:14:15    File "D:\ProgramData\FreeCAD 0.19\Mod\CfdOF\CfdConsoleProcess.py", line 52, in __del__
10:14:15      self.terminate()
10:14:15    File "D:\ProgramData\FreeCAD 0.19\Mod\CfdOF\CfdConsoleProcess.py", line 75, in terminate
10:14:15      if self.process.state() != self.process.NotRunning:
10:14:15  AttributeError: 'CfdConsoleProcess' object has no attribute 'process'
10:14:15  Traceback (most recent call last):
  File "E:/myWorkspace/myAirfoil2/myAirfoil/simulators/finiteTE/computing.FCMacro", line 32, in <module>
    solver_process = CfdConsoleProcess.CfdConsoleProcess(stdoutHook=solver_runner.process_output)
<class 'TypeError'>: __init__() got an unexpected keyword argument 'stdoutHook'

**Comment by oliveroxtoby** [comment]
Ah, this is due to some code refactoring I think. Try changing the line
```
solver_process = CfdConsoleProcess.CfdConsoleProcess(stdoutHook=solver_runner.process_output)
```
to
```
solver_process = CfdConsoleProcess.CfdConsoleProcess(stdout_hook=solver_runner.process_output)
```

**Comment by skunk69** [comment]
yes,right!thank you very much!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jaheyns/CfdOF"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月12日(星期二) 下午2:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jaheyns/CfdOF] errors from excuting FCMACRO (Issue #60)





 
Ah, this is due to some code refactoring I think. Try changing the line
 solver_process = CfdConsoleProcess.CfdConsoleProcess(stdoutHook=solver_runner.process_output)  
to
 solver_process = CfdConsoleProcess.CfdConsoleProcess(stdout_hook=solver_runner.process_output)
