### ISSUE TITLE
Need help installing dependencies

### ISSUE THREAD

**Issue by TheFGFSEagle** [jaheyns/CfdOF#61]
Hi everyone,
I'm trying to install CfdOF in my FreeCAD Addon manager, but it always says that it cannot find the dependencies. I have downloaded the OpenFOAM .deb files from their website and unpacked them into `$HOME`, so I have `$HOME/usr/lib/openfoam/openfoam2112/platforms/linux64GccDPInt32Opt` and `$HOME/usr/lib/openfoam/openfoam2112/platforms/tools`. Also I installed ParaView, also into `$HOME` so have a big bunch of libraries in `$HOME/usr/lib" and the binaries:
```sh
~$ ls usr/bin/
hydra_pmi_proxy  ospray_mpi_worker  paraview.conf  pvbatch       pvdataserver       pvpython       pvrenderserver       pvserver       qt.conf
mpiexec          paraview           paraview-real  pvbatch-real  pvdataserver-real  pvpython-real  pvrenderserver-real  pvserver-real  vrpn_server
```
I have the FreeCAD AppImage in `$HOME`, too, and I did no modifications to any of my environment variables. So, what else could be the problem ?

**Comment by oliveroxtoby** [comment]
That seems like an unusual installation location - is OpenFOAM working correctly from there? 
Are you setting the OpenFOAM install directory to $HOME/usr/lib/openfoam/openfoam2112?

Please provide all exact output - see https://forum.freecadweb.org/viewtopic.php?f=37&t=33492. You may be able to get some assistance on the forum.

**Comment by TheFGFSEagle** [comment]
> That seems like an unusual installation location - is OpenFOAM working correctly from there?

How can I verify this ?

> Are you setting the OpenFOAM install directory to $HOME/usr/lib/openfoam/openfoam2112?
Do you mean in Edit -> Preferences -> CFD ? If so, then no, because I don't have that item, which is logic because the addon doesn't install at all in the first place.

**Comment by TheFGFSEagle** [comment]
This the output I get when I try to install CfdOF in the Addon manager:
```
Some errors were found that prevent to install this workbench: Some errors were found that prevent to install this workbench. Please install the missing components first.
```
There are no log messages neither in the terminal (from which I'm running FreeCAD) nor in the output panel inside FreeCAD.

**Comment by luzpaz** [comment]
Please ask on the forum as [oliveroxtoby](https://github.com/oliveroxtoby) asked. Remember to always add your full [About](wiki.freecadweb.org/About) info.

**Comment by oliveroxtoby** [comment]
> > That seems like an unusual installation location - is OpenFOAM working correctly from there?
> 
> How can I verify this ?

Please consult www.openfoam.com

> Do you mean in Edit -> Preferences -> CFD ? If so, then no, because I don't have that item, which is logic because the addon doesn't install at all in the first place.

OK, that wasn't clear - thought you meant the dependency check in the preferences window was failing.

**Comment by oliveroxtoby** [comment]
> This the output I get when I try to install CfdOF in the Addon manager:
> 
> ```
> Some errors were found that prevent to install this workbench: Some errors were found that prevent to install this workbench. Please install the missing components first.
> ```

My guess would be an issue with matplotlib in your python installation. If you are using version 0.19, maybe try 0.20 as the addon manager has been revamped and will probably give you more complete information.

**Comment by TheFGFSEagle** [comment]
@oliveroxtoby okay, I'll try that - I actually DO have 0.19.

**Comment by TheFGFSEagle** [comment]
Thanks for the tip - I was actually able to install CfdOF without any errors with the 0.20 version !
